### ISSUE TITLE
T-shirt prints [front] | Logo or app icon?

### ISSUE THREAD

**Issue by iteles** [dwyl/print-me#1]
I originally put together a few options for the prints (rough drafts, not print quality):
![dwyl-tee -charcoal-front-1-colour](https://cloud.githubusercontent.com/assets/4185328/8146394/10e96fca-122d-11e5-92e0-9c3c3ec30d72.jpg)
![dwyl-tee -green-front-1-colour](https://cloud.githubusercontent.com/assets/4185328/8146392/10e82af2-122d-11e5-9c31-5a93aeb05d37.jpg)
![dwyl-tee -charcoal-front-2-colour](https://cloud.githubusercontent.com/assets/4185328/8146391/10e64782-122d-11e5-9692-737d38d149c4.jpg)
![dwyl-tee -charcoal-front-2-colour-white-l](https://cloud.githubusercontent.com/assets/4185328/8146393/10e87732-122d-11e5-8dc8-84dda19ef6b9.jpg)
![dwyl-tee -grey-front-2-colour](https://cloud.githubusercontent.com/assets/4185328/8146395/10e9c42a-122d-11e5-96f0-372b399723a4.jpg)

@nelsonic's comment to this [here](https://github.com/dwyl/start-here/issues/16) was:
![dwyl-tee -nk-tee-app-icon-print-comment](https://cloud.githubusercontent.com/assets/4185328/8146402/5cbf8704-122d-11e5-9ccd-1828f510f285.png)

**Comment by iteles** [comment]
I see your point. You're saying that we want to make the _icon_ be our recognisable brand, we're not too fussed about the logo itself. _It's worthwhile having the logo on the website because it's nice to see where it comes from (the 'L' morphing into a 'tick' in the heart), but not necessary on everything).

I think **there _is_ such a thing as too big a logo on the front**, if we're giving these out we want people to actually **wear them**, not just in front of us! The [bithound t-shirts](https://twitter.com/kellybraiden/status/440548312387563522) are probably about the limit of the size of something you can plaster across someone's chest without being obnoxious :stuck_out_tongue: 

The point about the app icon is very valid, but the white print on a colour looks... I'm a big fan of simplicity but I think this just looks _**So Bland**_ that no one will look at it twice:
_(NB. Our logo font is [Decker](http://www.fonts2u.com/decker.font) which isn't working on my computer at the moment, so these are mocked up using [Cabin](https://www.google.com/fonts/specimen/Cabin) instead)_

![dwyl-tee -charcoal-front-icon-1-colour](https://cloud.githubusercontent.com/assets/4185328/8146510/3c01f01e-1233-11e5-8421-405f7631dbf4.jpg)
![dwyl-tee -green-front-icon-1-colour](https://cloud.githubusercontent.com/assets/4185328/8146518/9633d0e8-1233-11e5-86b7-7cb2278229ad.jpg)

It **for sure** doesn't work on the charcoal or grey, the contrast in ink vs t-shirt colour is way too strong and those t-shirts are just begging for some colour in the print. It _could work_ for green or red. Maybe:

![dwyl-tee -green-front-icon-motto-1-colour](https://cloud.githubusercontent.com/assets/4185328/8146541/472f08c0-1236-11e5-98e9-8632a06a43d0.jpg)
![dwyl-tee -red-front-icon-motto-1-colour](https://cloud.githubusercontent.com/assets/4185328/8146540/472dccda-1236-11e5-89a3-2fbc8cd9a13b.jpg)

**Comment by iteles** [comment]
The thing I **feel most strongly about** is that we should have **the actual words _do what you love_ in a very visible location** linked to our logo, as _everyone_ identifies with that feeling and it'll make people much more likely to want to support us and wear the t-shirt when we're not around.
We _want_ the association of our logo/name with this saying - Doing what you love is the kind of club everyone wants to be part of :wink:

**Comment by nelsonic** [comment]
Agreed.
Do what you love
_or_
**Do**ing
**What**
**You**
**Love**?

Should be on the front (small) and/or the back (large) ...

**Comment by NataliaLKB** [comment]
@iteles regarding the original set of t-shirts, the 3rd one (the logo you guys actually paid for) is my favourite. 

If you guys do go ahead with the app icon, I also think it is a bit too bland on monochrome t-shirts however still nice on the coloured ones. 

Though I don't think it is cost effective, it may be a good idea to have a few t-shirts of each printed and compared. I would say my personal favourite is still the main logo on the black/dark grey t-shirt (but I am probably bias because I wear a lot of black).

Also, @nelsonic I completely agree with your last comment. Having that small at the back would be eye catching. May even make a passer-by stop the person wearing the t-shirt to ask what it is about.

**Comment by iteles** [comment]
Issue for the back print :arrow_right: #3 :+1:

**Comment by iteles** [comment]
![screen shot 2015-06-14 at 20 06 28](https://cloud.githubusercontent.com/assets/4185328/8150022/f61031da-12d0-11e5-926c-e5e16045ecaf.png)
![screen shot 2015-06-14 at 20 05 54](https://cloud.githubusercontent.com/assets/4185328/8150023/f6122ea4-12d0-11e5-9d41-1fa624db5aba.png)
![screen shot 2015-06-14 at 20 08 49](https://cloud.githubusercontent.com/assets/4185328/8150026/3740e05a-12d1-11e5-9064-2ee45219c8d5.png)

**Comment by NataliaLKB** [comment]
@iteles @nelsonic asked Gregory (hope you don't mind). He liked the colourful shirts quite a lot, but ultimately preferred the main logo to the app logo on a t-shirt.

**Comment by nelsonic** [comment]
@NataliaLKB I like the main logo. It was my favourite during the logo competition and I'm glad it got the most votes.
but, don't like the fact that the "L" (when integrated into the heart) looks the "wrong way round" when we think about it as a "Tick". 

Imagine if the [**Nike Swoosh**](https://en.wikipedia.org/wiki/Swoosh) was inverted ("_the wrong way round_") ... 

![swoosh_inverted](https://cloud.githubusercontent.com/assets/194400/8150165/98ec56e0-12d6-11e5-8e3f-6390e6f2db9c.jpg)

would it still look like a Tick? This just reminds me of _fake_ nike trainers from a Moroccan Market...

![fake nike trainers](http://www.2015airjordan.com/images/jordan/fake_barkley_posite_76ers_for_sale_nike_barkley_foamposites_max.jpg)

That's how I feel about the L with the heart. it **_is**_ our logo but "_the wrong way round_".

![dwyl-logo-tick-inverted](https://cloud.githubusercontent.com/assets/194400/8150223/5227ea78-12d9-11e5-9c73-9f91ec307b20.png)

Having a tick inside a heart says **_Do Love**_ which is the _essence_ of what we stand for. 
(the "what you" is _implied_)
![dwyl-logo-tick-right](https://cloud.githubusercontent.com/assets/194400/8150322/f8f00cde-12dc-11e5-996d-81c3f5fd491b.png)

**Comment by NataliaLKB** [comment]
@nelsonic that is understandable. 

But I will say that I never noticed it was a tick until you pointed it out! It is much more appealing when you think of it that way.

**Comment by iteles** [comment]
**Conclusions:**
- We split the heart and the dwyl lettering: In the end we began to move away from the idea of the heart being incorporated into the 'L' but were still very much into the idea of the logo being the heart with the tick. We therefore decided to go with splitting the two on the t-shirts
- Larger 'Do what you love' (long form) lettering
- Inclusion of `.io` on the front as well - I am less convinced about this one myself but it certainly ensures that there is some curiosity as to what the `io` is there there for
- Centred heart as having the heart to the left doesn't work on women's t-shirt cuts

![screen shot 2015-06-14 at 20 05 54](https://cloud.githubusercontent.com/assets/4185328/8150023/f6122ea4-12d0-11e5-9d41-1fa624db5aba.png)
![small-tee-final-design](https://cloud.githubusercontent.com/assets/4185328/8434968/9c38dbc6-1f46-11e5-99a4-391017e6414a.jpg)
