### ISSUE TITLE
Hexagon Stickers?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/print-me#15]
Showcase: http://hexb.in/
Spec: https://github.com/terinjokes/StickerConstructorSpec
@alanshaw where did TableFlip get their hex stickers printed?
Suppliers: https://github.com/terinjokes/StickerConstructorSpec/wiki/Vendors
Anyone used https://hexi.pics/help_en (recommended by @maxogden)

**Comment by alanshaw** [comment]
We got ours from [diginate](https://www.diginate.com/). They also now occasionally send me a money off offer to order more.

**Comment by nelsonic** [comment]
Oh... interesting. @alanshaw 
Just did a quick quote: https://www.diginate.com/quote/?product=metallic-sticker&shape=custom&material=sparkly&supply_option=individuals&diameter=&width=5.08&height=5.08&quantity=100&quote=
What _kind_ of "money off offer" (_promo code please..._ :wink: )

<img width="1003" alt="diginate-sticker-quote-100" src="https://cloud.githubusercontent.com/assets/194400/9897816/d14454c2-5c44-11e5-80dd-4e01f1e260b1.png">

**Comment by nelsonic** [comment]
@alanshaw did you get the dimensions of your stickers to match the Nodeschool (etc.) size? 
would you mind sending us the precise details for the order you placed? (_please/thanks!_)

**Comment by nelsonic** [comment]
@iteles can you jump on this or assign it to someone else who can do stickers?
e.g: can we pay someone with photoshop skills £20 to convert our existing sticker into a Hex and get it off to the printers on Tuesday? we **_need**_ these ...

**Comment by iteles** [comment]
@nelsonic No problem, hadn't quite realised we **needed** these! On my list for this weekend.

**Comment by nelsonic** [comment]
Its not "_urgent_" the way getting our _app_ working is... so it can wait another couple of weeks ...

**Comment by nelsonic** [comment]
But it would be good to have them for the next [**lnug**](http://lnug.org/) or LWC _for example_ ...

**Comment by iteles** [comment]
The next LNUG is 23rd September (which means even if we got them to the printers _yesterday_ they wouldn't be ready on time) _but_ we'll have them for the next one :+1:

**Comment by nelsonic** [comment]
Yeah, sorry I meant the next one ...

**Comment by iteles** [comment]
Good example with ai file: https://github.com/nodeschool/nodeschool.github.io/tree/source/images/make-a-sticker

**Comment by nelsonic** [comment]
Sweet. who do we know that can do this?

**Comment by iteles** [comment]
This is approximately a 10 minute job for anyone with AI, or $35 on a remote working website.

**Comment by iteles** [comment]
What we have to decide is whether to include dwyl.io on the sticker or not (given I don't think I've many a hex sticker with a website on it... except possibly workshape.io)

**Comment by nelsonic** [comment]
I think its pretty _pointless_ to _not_ include the website on the sticker. (IMO)

**Comment by alanshaw** [comment]
Same as here https://github.com/nodeschool/berlin/issues/3#issuecomment-60057104

**Comment by iteles** [comment]
Thanks @alanshaw! :+1:

**Comment by iteles** [comment]
@nelsonic These have been allocated as a task and we should have the files by the end of the week

**Comment by iteles** [comment]
<img width="315" alt="dwyl-hex-sticker -no-border" src="https://cloud.githubusercontent.com/assets/4185328/10104227/6432b1ae-63a0-11e5-9b07-bcd2f8271c7d.png">

Just waiting on decisions in the next couple of days to order :+1:

**Comment by nelsonic** [comment]
LIke it. (_but don't **love** it_) ...
Print-em.
How many? 100?

**Comment by iteles** [comment]
I have to say, I think the version with the border looks nicer:
![dwyl-hex-sticker -with-border](https://cloud.githubusercontent.com/assets/4185328/10104659/bb887ae0-63a2-11e5-8ea5-570c593f25b8.jpg)

**Comment by nelsonic** [comment]
@iteles Lets order 50+50 of border / no-border 
and let the people decide. Please.

**Comment by alanshaw** [comment]
FWIW I'd make the border width the same size as the line width for the heart (if it's not already) and make both the heart and dwyl a little smaller so they're further from the edge. I'd also make sure the distance between the border and the text/heart are equal al the way round. i.e. it looks as though the distance from the "d" to the bottom left border is _less_ than the distance from the top left of the heart to the top left border.

**Comment by nelsonic** [comment]
Agree with Alan. :+1:

**Comment by iteles** [comment]
Thanks @alanshaw, totally agree.

**Comment by nelsonic** [comment]
@iteles did you get the final design with Alan's suggestion of equalising the border and logo width?

**Comment by iteles** [comment]
Score.

![img_6307](https://cloud.githubusercontent.com/assets/4185328/10866577/b5cb3a74-802c-11e5-8957-6d4539d32196.jpg)
![img_6308](https://cloud.githubusercontent.com/assets/4185328/10866578/b5e4d89e-802c-11e5-952f-60b55bf00d73.jpg)

**Comment by HasseNasse** [comment]
Hey!
hexpace.net is a sticker shop which specializes in hexagon techy stickers with custom made designs.

Regards
