### ISSUE TITLE
T-shirt colours

### ISSUE THREAD

**Issue by iteles** [dwyl/print-me#2]
Originally we'd talked about charcoal and grey t-shirts and teal ones but we can't get teal ones in the UK.

[_Comment below from here_](https://github.com/dwyl/start-here/issues/16)
![dwyl-tee -nk-tee-colour-comment](https://cloud.githubusercontent.com/assets/4185328/8146352/807a3f74-122b-11e5-805d-d3298d31e894.png)

Sadly, though I love the - bright pink - berry colour, it's pretty hard to get a hold of it in the UK. 
Here are the colours [our current supplier (Firelabel) stocks](http://www.firelabel.co.uk/t-shirts/mens/crew-neck-t-shirts/cv3413-canvas-triblend-t-shirt.html):
![dwyl-tee -firelabel-available-colours](https://cloud.githubusercontent.com/assets/4185328/8146371/5426b154-122c-11e5-9ef5-6fdd9864c4f1.png)

The red and the green have always been my favourites, but having tried multicolour logos on them, it's pretty clear that only a plain white print would work well on those 2 colours in particular.
So first we have to solve issue #1 :blush: 

_P.S. Hey, it's summer! I'm happy to only have happy, sunshiney colours until we print our own_

**Comment by nelsonic** [comment]
I'm super happy to use a plain white print for the _Alpha_ T's.
Has the printer said we can only do one color of T?
Or do we have to order a min quant for each color?

**Comment by iteles** [comment]
No min quantities, we can mix and match!

**Comment by iteles** [comment]
So we looked at the design on multiple colours and decided it didn't look good on charcoal (too bland as per #1) so we offered everyone the choice of blue, navy or red.
Overwhelmingly people chose blue, with 5% going for red and 10% going for navy - let's see how people feel once the t-shirts show up in real life!

**Comment by iteles** [comment]
From the design proofs!
![screen shot 2015-06-30 at 17 07 56](https://cloud.githubusercontent.com/assets/4185328/8435680/9c5ad006-1f4a-11e5-87d6-10b22e3e4d55.png)

**Comment by nelsonic** [comment]
A little annoyed I'm not getting a Pink one... :disappointed:

**Comment by iteles** [comment]
It's not pink, it's red. And you're getting one, just in August instead of July because they were out of stock of the red Ms!
