### ISSUE TITLE
More t-shirts?

### ISSUE THREAD

**Issue by iteles** [dwyl/print-me#20]
We've run out of men's M t-shirts and pretty much all ladies sizes.

We need to make more for the summer!

Questions:
- What do we need to change about the prints?
- Should we look into different t-shirts (materials)?
- How many and what sizes do we need?

If you have thoughts on **any** of these, please drop in a comment!

**Comment by nelsonic** [comment]
I ended up using my navy T-shirt (_way_) more than the others so I would prefer a darker one. 
We should get any colour(s) people want IMO.

**Comment by heron2014** [comment]
@iteles I really like the material of the t-shirts, good quality and is softie (if  that's the word) :blush:

**Comment by Jbarget** [comment]
Re: sizes, after a few washes the tshirts shrink a bit so even though im a 'medium' id take a large (if im allowed one :) )

**Comment by jackcarlisle** [comment]
I'm a big fan of the blue ones! Size xl so there's room for it to shrink (or me to grow 🐷)

**Comment by nelsonic** [comment]
@jackcarlisle you're more like an **S** ...
unless you're planning on remote-working from an all-inclusive resort and setting up your work-station in the Buffet... 🍨

**Comment by harrygfox** [comment]
hello please may i have tshirt

**Comment by jrans** [comment]
@iteles Material is very good!

As for print. I think a small logo on the left chest  (dwyl heart with dwyl written underneath) and then dwyl  smally printed on top back is most stylish but you may want to push harder on the message. I always feel people will try to find the logo and notice it more if subtle and words everywhere is too in your face. But hey thats just me!

**Comment by heron2014** [comment]
Really good suggestion by @jrans !! :+1:

**Comment by jackcarlisle** [comment]
@nelsonic that is the dream 🙌🏼

**Comment by iteles** [comment]
They'll look like this!

**Men's:**
<img width="557" alt="screen shot 2016-09-02 at 12 34 28" src="https://cloud.githubusercontent.com/assets/4185328/18202731/ed529a0e-7109-11e6-8a65-336db4f97897.png">
<img width="557" alt="screen shot 2016-09-02 at 12 33 39" src="https://cloud.githubusercontent.com/assets/4185328/18202732/ed53877a-7109-11e6-925a-c45a37eb8d81.png">

**Ladies:**
<img width="495" alt="screen shot 2016-09-02 at 12 34 53" src="https://cloud.githubusercontent.com/assets/4185328/18202736/fa2c5648-7109-11e6-866d-ae40c0a23d9a.png">
<img width="464" alt="screen shot 2016-09-02 at 12 34 03" src="https://cloud.githubusercontent.com/assets/4185328/18202737/fa2c35f0-7109-11e6-93c7-ac95128822a3.png">

**Comment by andrewMacmurray** [comment]
@iteles the new designs are 👌

**Comment by Jbarget** [comment]
is that @jrans working his magic in the black?

**Comment by nelsonic** [comment]
@Jbarget it certainly _looks_ like @jrans is the model for the Charcoal T... 😜 
https://youtu.be/yYCmhHFhopA

**Comment by ghost** [comment]
@iteles ok to close?

**Comment by nelsonic** [comment]
@iteles we're going to need to do another print run soon ... ⌛️ 
each FT should have 5 T-Shirts and 2 Hoodies #17 by April 1st. 📆 
I was **_reminded_ today** that @SimonLab, @harrygfox, @katbow, @jackcarlisle, @naazy, @mk4111, @shouston3, @RobStallion, @Conorc1000, @roryc89 & @Cleop  ***still*** don't have **Hoodies**! 😮 😢 
after [Headphones](https://github.com/dwyl/hq/issues/147) wearable "Merch" is the next best smile-maker. 😊 
@markwilliamfirth if u prefer to delegate apparel ordering (_so you can focus on other tasks_) 🎯 
@Cleop might be able to help do the supplier liaison if we ask her nicely. 😉
