### ISSUE TITLE
Rainbow Stickers?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/print-me#22]
What do people think of doing a batch of _rainbow_ DWYL stickers...? 🌈  ❤️  🤔 
like: 
![image](https://cloud.githubusercontent.com/assets/194400/22365540/f2aab534-e46f-11e6-82ce-2db8c4821bb5.png)
but with the **DWYL** logo...
https://github.com/dwyl/print-me/issues/15#issuecomment-152782503

**Comment by nelsonic** [comment]
@iteles I don't have the _original_ source files for the DWYL Logo... all I have is the PNG...
![dwyl-heart-only-logo](https://cloud.githubusercontent.com/assets/194400/22366777/4f96bb48-e476-11e6-9f1c-6977c2215a9b.png)
so when I try "cut out" the logo part,
to _apply_ it to the Rainbow BG I get this:
![dwyl-rainbow-sticker-background-fail](https://cloud.githubusercontent.com/assets/194400/22366369/2e577e9c-e474-11e6-9a19-355a2de1a23f.png)
with the teal border around the logo which is `#fail` ... 😞 

but here's the rainbow background: 
![rainbow-sticker-background](https://cloud.githubusercontent.com/assets/194400/22366218/6eabb590-e473-11e6-893c-4369fd0e4fbe.png)
so `if` anyone `else` wants to `try` the can...

**Comment by harrygfox** [comment]
@nelsonic Love it! It's [proudly inclusive](https://en.wikipedia.org/wiki/Rainbow_flag_(LGBT_movement)).

**Comment by naazy** [comment]
SO keen :rainbow_flag:

**Comment by Jbarget** [comment]
👍  fo sho
id be keen to see what the inverse looks like with the rainbow fill _in_ the DWYL heart

**Comment by harrygfox** [comment]
@Jbarget 
![rainbow heart](https://cloud.githubusercontent.com/assets/7805691/22373250/c1cd531c-e498-11e6-9662-f30eee45975c.png)
![rainbow heart inverse](https://cloud.githubusercontent.com/assets/7805691/22373330/2a6d8cf2-e499-11e6-8799-9c8b66e76873.png)

**Comment by katbow** [comment]
those look amazing! Super keen ❤️

**Comment by nelsonic** [comment]
Sounds like "_all_" we need to decide is 
what shape & size they are going to be and 
how many we are going to print ... 
(_should we do a small batch first to test...?_)

**Comment by iteles** [comment]
Do we want dwyl.io in there or just the heart?

Love the rainbow 🌈

**Comment by nelsonic** [comment]
@iteles **good _question_**... 🤔 

# Let's 🆎  _Test_ It!!

+ Print ***[two](https://www.youtube.com/watch?v=0dMofPfpJsE) batches*** one **with _and_** one ***without***.
+ Take both stacks of stickers  (_the same number in each stack_) to the next @LadiesOfCode meetup 
with a hand written post-it e.g:
![free-stickers](https://cloud.githubusercontent.com/assets/194400/22395323/cfd3a76a-e531-11e6-98dc-50b6891bd1df.JPG)

Without saying _anything_ `else` about the stickers, just see how many are _left_ of each kind at the end of the night. you'll have your _answer_. 😉 👍

**Comment by andrewMacmurray** [comment]
Love it 👌

**Comment by katbow** [comment]
Thoughts on this one with a transparent background for testing?
![dwyl_transparent](https://cloud.githubusercontent.com/assets/1287388/22398214/b0e90fda-e57b-11e6-95fe-fae5e26b63e3.png)

**Comment by sohilpandya** [comment]
@katbow I ❤️ the transparent one, but how about having the DWYL.io at the bottom?

**Comment by sohilpandya** [comment]
Something like this? Just a thought.. 💭 
![dwyl](https://cloud.githubusercontent.com/assets/2305591/22407352/d4e0a7fe-e65c-11e6-9fa5-d390a2afbb58.png)

**Comment by ghost** [comment]
Pride is Saturday, 24 June - Sunday, 9 July

So seems apt to order these now

**Comment by nelsonic** [comment]
@markwilliamfirth good plan. 👍 
you ordering plain or with `.com` ? 🤔

**Comment by ghost** [comment]
@nelsonic see https://github.com/dwyl/print-me/issues/27

**Comment by ghost** [comment]
@iteles how big were the last ones you ordered? Gonna suggest we go for 6cm x 6cm?

**Comment by iteles** [comment]
@markwilliamfirth You should have all the info you need from:

Alpha stickers, referenced in the readme: https://github.com/dwyl/start-here/issues/17#issuecomment-109280351
Hex ones in closed issues of this repo: https://github.com/dwyl/print-me/issues/15#

In short, looks like we've gone with 5cm in the past as per the 'standard' tech sticker 👍

**Comment by ghost** [comment]
Made an initial order of 30 of [this design](https://github.com/dwyl/print-me/issues/27#issuecomment-311343507), let's see how they look - if we want more we can order more 👍

**Comment by ghost** [comment]
These were ordered - closing issue

https://twitter.com/Sohil_is/status/882524856637693952

**Comment by ghost** [comment]
These faded very quickly on people's phones and laptops

![20170730_220914](https://user-images.githubusercontent.com/5732209/28819059-ddf0e27c-76a4-11e7-9397-e44d93e39c64.jpg)
![20170731_113821](https://user-images.githubusercontent.com/5732209/28819060-ddf48dbe-76a4-11e7-974f-c0ad9a12934c.jpg)
![20170731_113852](https://user-images.githubusercontent.com/5732209/28819061-ddf71066-76a4-11e7-80a6-744770196bcc.jpg)

We complained and now Diginate are sending us a free reprint with the new batch being a UV print to make them scratch resistant.

**Comment by ghost** [comment]
New ones of these were sent and they don't scratch! (have tested for over a month)
