### ISSUE TITLE
New Business Cards

### ISSUE THREAD

**Issue by ghost** [dwyl/print-me#25]
Needed for an event next Wednesday

Linked to:
https://github.com/dwyl/print-me/issues/7
https://github.com/dwyl/print-me/issues/18

**Comment by ghost** [comment]
@iteles could you drop any old business card designs including the designs for #7 into [this folder](https://drive.google.com/drive/folders/0B0XeQ2t5WSK2N2NwZ01pRmFybkE) please?

**Comment by iteles** [comment]
@markwilliamfirth Dropped in the whole file which has multiple png variations I toyed with. 
You'll also find the `psd` files in there, I created the originals in photoshop elements at the time.

**Comment by ghost** [comment]
@iteles which psd is the most recent design?

**Comment by iteles** [comment]
I don't actually like the old designs any more, I was hoping we could come up with a new one. Wasn't very clear about this on Wednesday it seems. My bad 👍

**Comment by iteles** [comment]
I've also just had a look and there are 6 psd files in there:
+ Front of landscape business card
+ Back of landscape business card
+ Front of websummit business card (exactly as above but with a different URL)
+ Back of websummit business card (exactly as above but with a different URL)
+ Front of portrait business card
+ Back of portrait business card

So I guess your question is did we go with landscape or portrait?
Landscape, as you can see from photo in the issue you referenced above: https://github.com/dwyl/print-me/issues/7#issuecomment-152782663

**Comment by ghost** [comment]
![business card - landscape - front](https://user-images.githubusercontent.com/5732209/27028948-58c3bf9c-4f5e-11e7-94eb-4d4f7f4dc428.png)

![business card - landscape - back](https://user-images.githubusercontent.com/5732209/27029058-a8afe5f8-4f5e-11e7-897a-eccea95304c9.png)

@iteles ok to send to printers?

**Comment by iteles** [comment]
@markwilliamfirth Thanks for this!

A few points:
+ These need to say our organisation's name somewhere on them (not just the information)
+ The column layout makes it feel like the things on the right are related to the things on the left (I was confused for a few seconds there) so I don't think it works as we'd hope
+ Please remove 'time tracking software', that's not really how we want to market what we'll do and in the meantime we can make a small run of 50 to test the card which won't need this (i.e. let's put a little more thought into how we include our product side for the next round)
+ We need a little more than 'Product Development' - I would suggest 'Digital product development' until we find a better term (hate 'digital'!)
+ '**Agile** & technical training'

**Comment by ghost** [comment]
![business card - landscape - back](https://user-images.githubusercontent.com/5732209/27029994-7e10a1e4-4f62-11e7-9a4c-e7c7926f8ef7.png)

@iteles updated

**Comment by iteles** [comment]
YES! :shipit: 

Let's do a small round this time as we might need/want to redesign these in line with our new website very soon!

(if you use printed.com, I recommend starting at 50 and push up until the price changes - when I had invites printed, it was the same price for 65 as it was for 80)

**Comment by ghost** [comment]
![business card - landscape - front2](https://user-images.githubusercontent.com/5732209/27030093-d4b5ef2c-4f62-11e7-9319-b90ede5b1900.png)

@iteles alternative version of front with company name - let me know which you prefer

**Comment by iteles** [comment]
@markwilliamfirth Actually genuinely don't mind for this small run - if you want to test no name, I'm happy to go with that.

Should it be 'co-working _space_'? A quick google shows almost all results use that terminology.

**Comment by iteles** [comment]
Note sure if you saw https://github.com/dwyl/print-me/issues/25#issuecomment-307752158 ?
I'll be at Mindwave on Wednesday, so please ship there.

**Comment by ghost** [comment]
@iteles yep - sorting printing now.

On the co-working point - I'm imagining 'Services' as being written after each service

Digital Product Development [Services]
Co-working [Services]
Agile & Technical Training [Services]

Co-working Space [Services] sounds a bit weird to me, co-working by itself sounds better to me, but can change if you'd prefer Co-working Space - they're your cards after all 😛

**Comment by iteles** [comment]
Co-working by itself just wasn't making much sense to me which is why I suggested an alternative . Like 'we do co-working'. Does that mean you work with others? Don't we all?

Maybe co-working services more explicitly would make sense?
As you prefer though :blush:

**Comment by ghost** [comment]
Well I think co-working is explanatory enough, but let me know what you want it to say and I can make the edits

**Comment by iteles** [comment]
Like I said - as you prefer! If you think it's enough, then let's go with that :+1:

**Comment by ghost** [comment]
Sent for printing:

http://samedaybusinesscards.co.uk (domain of http://www.simplyprint.com)

Medium Press (80% quality of high end press with a risk of banding unevenness of colour on the solid background)
50 Business Cards
Double Sided 350gsm
Silk Price: £30+VAT = £36

Have requested test print before proceeding to ensure sufficient quality

Have ordered for collection from:
[Same Day Business Cards, 40 Bowling Green Ln, Clerkenwell, London, EC1R 0NE
](https://www.google.co.uk/maps/place/Same+Day+Business+Cards/@51.5251254,-0.1094719,17z/data=!3m1!4b1!4m5!3m4!1s0x48761b4f8ca21b7d:0xb24887534f5b6a57!8m2!3d51.5251221!4d-0.1072832)
[7 minute walk](https://www.google.co.uk/maps/dir/''/Baird+House,+St+Cross+St,+London+EC1N+8UW/@51.5231308,-0.1120645,16z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x0:0xb24887534f5b6a57!2m2!1d-0.1072832!2d51.5251221!1m5!1m1!1s0x48761b4e7002c4ff:0x84e0d5e95e73b0db!2m2!1d-0.1075132!2d51.5211264!3e2) from MV office

Alternatively delivery can be requested (£6)
Order reference: T6120
support@simplyprint.com
0207 415 7014

**Comment by ghost** [comment]
@iteles they are now ready for collection. Let me know if you want me to arrange delivery instead.

**Comment by iteles** [comment]
@markwilliamfirth The cards or the test print?

I'll be at Mindwave on Wednesday and can pick them up 👍

**Comment by ghost** [comment]
@iteles the cards are done! They sent me a picture of the test print and it looked fine. When we do the next (proper) batch we might want to consider going super high quality though

**Comment by ghost** [comment]
Bulk order quote from simply print (for future reference):

Double Sided Business Cards
 
455gsm Silk
100 = £21.99+VAT
250 = £29.99+VAT
500 = £34.99+VAT
 
500gsm Matt Laminated – add £3+VAT to the above prices.

**Comment by iteles** [comment]
These were pretty rubbish, let's not use this company again.
(will add a photo asap)
