### ISSUE TITLE
Vote on Sticker Design Concepts

### ISSUE THREAD

**Issue by ghost** [dwyl/print-me#27]
Hi everyone!

Please vote for your design (https://github.com/dwyl/print-me/issues/22)

👍 for a vote (only thumbs count), you can vote for as many designs as you want

Depending on what the voting outcome is we may get only one design or a few designs printed

Designs will be refined and edges will be smoothed prior to printing, in designs 3 and 4 the white is transparent

**Comment by ghost** [comment]
![pride-design-1](https://user-images.githubusercontent.com/5732209/27587539-ae374964-5b3c-11e7-8a90-769dc7bb7121.png)

**Comment by ghost** [comment]
![pride-design-2](https://user-images.githubusercontent.com/5732209/27587543-b3a414c2-5b3c-11e7-8a5a-6afdc6f49c63.png)

**Comment by ghost** [comment]
![pride-design-3](https://user-images.githubusercontent.com/5732209/27587550-b835a9ec-5b3c-11e7-821f-cad2f3ad47ac.png)

**Comment by ghost** [comment]
![pride-design-4](https://user-images.githubusercontent.com/5732209/27587560-bd85b194-5b3c-11e7-85b7-1ef171cd2019.png)

**Comment by harrygfox** [comment]
@markwilliamfirth why are the colours different from here https://github.com/dwyl/print-me/issues/22#issuecomment-275941128

Are these official pride colours?

**Comment by ghost** [comment]
@harrygfox [yep](https://commons.wikimedia.org/wiki/File:Gay_flag.svg)!
