### ISSUE TITLE
T-shirt prints [back] | Design and location

### ISSUE THREAD

**Issue by iteles** [dwyl/print-me#3]
Three questions:

**1. Do we need a print on the back at all?**
I think it's a nice touch so people who you're not specifically talking to can see that you're supporting dwyl, but it's **only _strictly necessary_ if we're going to use the location to display the URL** if isn't already on the front. 
_Should_ we have the URL on the t-shirt? Logically it makes sense to tell people where to find us but will it make people less likely to wear the t-shirt?

**2. If we have back prints, where should we put them?**
The industry trend is to either not have back prints or to put the _at the top, just below the neckline_. I think **the trend is wrong**.
This might be _pretty_ but it's covered by anyone (of either gender) with long hair (and if you're going to bother thinking about making a ladies t-shirt, you might as well put some _actual_ thought into it given the amount of women with longer hair).

SO:
**Bad locations:** Small of back & just above the bottom hem of t-shirt below the waist - both of these draw attention to places that don't need attention drawn to them.

**Viable options:**
- Middle of the back
  ![dwyl-tee -back-middle](https://cloud.githubusercontent.com/assets/4185328/8146578/69269d72-123a-11e5-8523-0357d877b804.png)
- Flipped 90 degrees anti-clockwise so it's written up the side of the t-shirt
  ![dwyl-tee -back-side-print](https://cloud.githubusercontent.com/assets/4185328/8146579/7eeaa69e-123a-11e5-9c51-808e49a0e44b.png)

**3. If we have a back print, is it overkill to add the logo _again_?**
It might be. But people who see the back might not see the front and I think it adds a little flair to the back...
![dwyl-tee -back-middle-icon-right](https://cloud.githubusercontent.com/assets/4185328/8146585/948a198a-123a-11e5-8186-0cd55c13e22b.png)
![dwyl-tee -back-middle-icon-left](https://cloud.githubusercontent.com/assets/4185328/8146586/948c2536-123a-11e5-86c5-58c8bba57900.png)

**Comment by nelsonic** [comment]
**Do**ing
**What**
**You**
**Love**?
[logo] www.dwyl.io

**Comment by iteles** [comment]
Do you not think that will make people feel like walking billboards rather than people who are getting a cool t-shirt they identify with to wear? 😕

**Comment by iteles** [comment]
Hm. In practise I can't seem to make it not look like an insurance advert:

![dwyl-tee -back-middle-with-question](https://cloud.githubusercontent.com/assets/4185328/8149577/364914a8-12c0-11e5-9d26-728733b93a38.png)
![dwyl-tee -back-middle-with-question-www](https://cloud.githubusercontent.com/assets/4185328/8149585/77dfa062-12c0-11e5-8137-26f14fdecb77.png)
![dwyl-tee -back-middle-with-question-top](https://cloud.githubusercontent.com/assets/4185328/8149623/01c8dc34-12c2-11e5-8e8d-81fa56e78202.png)

**Comment by iteles** [comment]
We went with this on the back for MVP purposes. We'll need to gather people's opinions.
