### ISSUE TITLE
Where are the files for the latest stickers, etc?

### ISSUE THREAD

**Issue by iteles** [dwyl/print-me#31]
@markwilliamfirth I needed a dwyl [logo file](https://github.com/dwyl/hq/issues/252) for something I've been shortlisted for, so went to look for our latest stickers etc but I couldn't find anything recent  in either the ['Logos' folder](https://drive.google.com/drive/folders/0B3KbLmXw1O5CaVFxSUxrd0xsV0k) or the ['Merchandise' folder](https://drive.google.com/drive/folders/0B0XeQ2t5WSK2V3F4bE5qWmZTcjQ).

Where should I be looking?

**Comment by iteles** [comment]
@rub1e We didn't get an answer on this either, so could you keep an eye out for these as part of clearing up the mess that is our Google Drive https://github.com/dwyl/hq/issues/428 ?

But better yet, because as I said above, the files are in any of the logical places, could you please also log into our diginate account and grab what we can from them?

**Comment by rub1e** [comment]
Logos are now saved in `Marketing > Logos` per https://github.com/dwyl/hq/issues/428

There are also other assets are saved in `Marketing > dwyl Stash`

The only thing is that I totally missed the `diginate` comment! They don't seem to let you download your files and I checked in 👻 's sent items and there's nothing there, so I'll email diginate and save any files in the `Stash` folder

**Comment by iteles** [comment]
That's great, I don't understand why they weren't put in the google drive somewhere in the first place 🤦‍♀️

**Comment by rub1e** [comment]
Closing as question is answered and all relevant info is contained in the readme
