### ISSUE TITLE
Business card | Back

### ISSUE THREAD

**Issue by iteles** [dwyl/print-me#6]
We'll get 50 [business cards](http://uk.moo.com/products/original-business-cards.html) made for each of Nelson and Ines to start off with.  
The purpose is to:
- Have something in our pockets in case we're asked about what we do and the people would like to stay in touch with us
  - Preferably something they won't throw away but will actually be something useful and a positive reminder of our app and ideals
- Testing out a couple of different designs (and printed colours) to see how they look - hence the small runs.

Related to issue #7 on the design of the front.

**Comment by iteles** [comment]
**Suggestions:**

![dwyl-business-card -front-landscape-d](https://cloud.githubusercontent.com/assets/4185328/8309513/ddcc5ace-19c2-11e5-9218-38c34d61695c.png)
![dwyl-business-card -front-portrait-c](https://cloud.githubusercontent.com/assets/4185328/8309518/de22c9c2-19c2-11e5-8df6-2ba00e5986b3.png)
![dwyl-business-card -front-portrait-b](https://cloud.githubusercontent.com/assets/4185328/8309519/de3323ee-19c2-11e5-8ced-6bed205bb10b.png)
![dwyl-business-card -front-portrait-a](https://cloud.githubusercontent.com/assets/4185328/8309517/de16ad18-19c2-11e5-9535-81349c1e5f10.png)
![dwyl-business-card -front-landscape-c](https://cloud.githubusercontent.com/assets/4185328/8309514/ddd0a4c6-19c2-11e5-918b-bcd152736207.png)
![dwyl-business-card -front-landscape-b](https://cloud.githubusercontent.com/assets/4185328/8309515/ddd4b91c-19c2-11e5-9267-2139a1a3fa37.png)
![dwyl-business-card -front-landscape-a](https://cloud.githubusercontent.com/assets/4185328/8309516/ddeacd9c-19c2-11e5-9414-f3fda3a913ed.png)

**Comment by iteles** [comment]
I really like the idea of having the words 'do what you love' across the front with our icon, so people might keep them and use them as little prints/put them on display. Haven't quite hit upon the right combination of the slogan and the website on the front. Feeling a bit meh about all of these.

I think I might get the fourth one down (the last portrait one) just to be a little different.
@nelsonic, which of these (or any other ideas) would you like?

**Comment by iteles** [comment]
Another option:

![dwyl-business-card -front-portrait-d](https://cloud.githubusercontent.com/assets/4185328/8310268/b0ae262c-19c6-11e5-9b49-079fc2941ec3.png)

**Comment by nelsonic** [comment]
@iteles I looked at these (_while you were designing them and_) when the issue notification came through yesterday. While I :+1:  **_all**_ of them, I don't :heart: any. (_sorry if that feels harsh..._)

I _like_ the **_handwriting font**_ you used, but don't like the **_ALL CAPS**_...

**Comment by iteles** [comment]
That's a function of the brush script font. 
Also, that's not harsh, as I mentioned, that's exactly how _I_ feel about them.

**Comment by iteles** [comment]
@nelsonic Worth considering whether this should be looked at again in light of https://github.com/dwyl/hq/issues/28#issuecomment-148154071

**Comment by nelsonic** [comment]
@iteles yes, this needs to be done **_ASAP**_.

**Comment by nelsonic** [comment]
@iteles what do you need (_from me/anyone else_) to get this done _today_?

**Comment by iteles** [comment]
I _really like_ the idea of people using the card as a little print and I think having the words 'do what you love' in brush script go a long way towards that. However, it also means that people won't associate the heart with 'dwyl', they'll associate it with 'do what you love' which doesn't get us where we wanted...

If I could, _this_ would be my business card and yours would be the standard one we used for our stickers.

<img width="993" alt="screen shot 2015-10-22 at 00 53 10" src="https://cloud.githubusercontent.com/assets/4185328/10653425/6f891194-7857-11e5-9904-52d9ba1e5c50.png">

**Comment by nelsonic** [comment]
we need to "_enable_" tracking on our business cards. 
yours needs to be: `dwyl.io/ibc` and mine will be `dwyl.io/nbc` (_where bc is business card_)

**Comment by nelsonic** [comment]
Or... if we are only getting one card printed then `dwyl.io/bc1` 
also, We need to research how to give people "free for ever if you help us beta test and request/vote for features"...

**Comment by iteles** [comment]
_That_ is for #7. Do we need to split yours and mine or just _business cards_ as a means of measurement? I ask because this feels like a competition I may not win :wink:

**Comment by iteles** [comment]
I _realise_ the need for the tracking and I think it's the logical step. But _intuitively_, it makes me feel like it's going to look like a complicated URL, not worth the work. `io` already seems to confuse even _young_ non-technical people (anecdotally).

`www.dwyl.io/bc`

**Comment by nelsonic** [comment]
That's why we need to make it _worthwhile_ to people...

> _Help us_ `Beta Test` _our App and we will give you_ **_life-time free access worth $40/year**_.

**Comment by iteles** [comment]
OK, we need to make these happen tomorrow, so we can talk about the offer then. 
We _do_ also need to decide what the design on the front will be, irrespective of the URL.

**Comment by nelsonic** [comment]
Agreed. So glad you're sorting this. :+1:

**Comment by iteles** [comment]
I was having issues with the messiness around the 'what' and also wanted to try out the `/bc`

<img width="995" alt="screen shot 2015-10-22 at 15 34 37" src="https://cloud.githubusercontent.com/assets/4185328/10668123/a02036e0-78d2-11e5-99b6-899e9235d51e.png">

**Comment by nelsonic** [comment]
(**_IMO**_...) the url should not extend beyond the words. 
@markwilliamfirth your :eyes: are requested...

**Comment by iteles** [comment]
<img width="992" alt="screen shot 2015-10-22 at 20 55 23" src="https://cloud.githubusercontent.com/assets/4185328/10676607/50e1ec22-78ff-11e5-96a3-2f65c5e676ec.png">

**Comment by nelsonic** [comment]
_Betterer_ (_IMO_)
feels a few _pixels_ off...
But not worth wasting any more time on.

**Comment by iteles** [comment]
<img width="250" alt="screen shot 2015-10-22 at 21 01 49" src="https://cloud.githubusercontent.com/assets/4185328/10676738/24a6a674-7900-11e5-959d-77608d07d5b0.png">

The question is do we keep `bc`? Or split them into more than one `bc`?

**Comment by nelsonic** [comment]
If you shift the domain to the left then we can use sharpies to write custom urls on the cards...

**Comment by iteles** [comment]
Getting **100 /websummit** of these and **100 dwyl.io** (no`/`) made for **_each_** of us, so 400 cards total. Let me know if you want less of either!

<img width="397" alt="dwyl-final-business-cards-back" src="https://cloud.githubusercontent.com/assets/4185328/10719195/f988b012-7b7b-11e5-84e3-e971a3b63e97.png">

**Comment by iteles** [comment]
Alpha business cards done. Road testing these at the [Web Summit](https://websummit.net/) in a couple of days and gathering feedback on anything that confuses people or questions they ask.

![img_6317](https://cloud.githubusercontent.com/assets/4185328/10866583/f9e7239e-802c-11e5-904d-6dd7b93aa6e1.jpg)
