### ISSUE TITLE
Why do people (still) print Business Cards? (More importantly, what is our objective with dwyl cards?)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/print-me#8]
Are business cards a relic of a time before we had smartphones and could "_lookup_" people on the spot and connect with them on LinkedIn?

I still think having _physical_ Cards are highly relevant in 2015,
but having a card _just_ to give someone your contact details is obsolete.

If the card does not have something _special_ I feel like its a _missed opportunity_.

Relates to: #6 and #7

**Comment by nelsonic** [comment]
The _reason_ I asked that question was not to put in _doubt_ the validity of ordering the cards,
instead I want us to _focus_ on the _exact objective_ of the card ... what is our desired (call-to-)action when handing out a card?

**Comment by iteles** [comment]
I totally agree that there actually needs to be a purpose to having business cards.

For an **MVP stage**, the main point for me is for people to have something both that makes them smile and to remember us by - not as people, but as an organisation with a great set of ideals that they identify with. The main one being 'do what you love'; it's a sentiment people agree with.

Hopefully they'll want to keep up with our progress and it will also spur them to check out the website. Also, I find that twitter/linkedin/email contacts jotted down digitally are easy to forget about unless there's something specific you need from that person. A business card (if good) is memorable and reminds you to look that person up or get in touch - even if it's just the one time you pick it up to put it in the recycling bin (not ours hopefully!).

**Comment by ghost** [comment]
ok to close?
